[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stablefun = "STBL1grL2qPy4fzVk7Ko2kY8Cb7EwKRYaGHaAptNdSr"

[programs.localnet]
stablefun = "STBL1grL2qPy4fzVk7Ko2kY8Cb7EwKRYaGHaAptNdSr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
